default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Root@123

development:
  <<: *default
  database: testing_development

test:
  <<: *default
  database: testing_test

production:
  <<: *default
  database: testing_production
  username: testing
  password: <%= ENV["LEARNING_GRAPE_API_DATABASE_PASSWORD"] %>
